[versions]

# plugins
shadow = "7.1.2"
blossom = "1.3.1"
spotless = "6.12.1"
nexusPublish = "1.1.0"

# testing
junit = "5.9.2"
mockito = "4.11.0"

# general
annotations = "23.1.0"
slf4j = "1.7.36"
geantyref = "1.3.14"

[libraries]

# testing
junitApi = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junitParams = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
junitEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
mockitoInline = { group = "org.mockito", name = "mockito-inline", version.ref = "mockito" }
mockito = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockito" }

# general
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
geantyref = { group = "io.leangen.geantyref", name = "geantyref", version.ref = "geantyref" }

[bundles]

mockito = ["mockito", "mockitoInline"]
junit = ["junitApi", "junitParams", "junitEngine"]

[plugins]

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
nexusPublish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexusPublish" }
