[versions]

# plugins
shadow = "7.1.2"
blossom = "1.3.1"
spotless = "6.15.0"
nexusPublish = "1.1.0"

# testing
junit = "5.9.2"
mockito = "5.1.1"

# general
annotations = "24.0.0"
slf4j = "2.0.6"

[libraries]

# testing
junitApi = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junitParams = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
junitEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
mockitoInline = { group = "org.mockito", name = "mockito-inline", version.ref = "mockito" }
mockito = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockito" }

# general
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }

[bundles]

mockito = ["mockito", "mockitoInline"]
junit = ["junitApi", "junitParams", "junitEngine"]

[plugins]

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
nexusPublish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexusPublish" }
